name: testpip
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  hooks_riverpod: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
