name: Flutter Pipeline

on:
  push:
    branches:
      - main

jobs:
#  build-and-test:
#    runs-on: ubuntu-latest

#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2

#      - name: Set up Flutter
#        uses: subosito/flutter-action@v2
#        with:
#          flutter-version: 2.x

#      - name: Build and test
#        run: flutter test

  build-android:
#    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 2.x

      - name: Build Android APK
        run: flutter build apk

      - name: Save logs to a file
        run: |
          mkdir logs
          mv build/app/outputs/apk/release/app-release.apk logs/app-release.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Android Artifact
          path: logs/

  build-ios:
#    needs: build-and-test
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 2.x

      - name: Build iOS app
        run: flutter build ios --release --no-codesign

      - name: Save logs to a file
        run: |
          mkdir logs
          mv build/ios/iphoneos/Runner.app logs/Runner.app

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: iOS Artifact
          path: logs/
