name: Flutter Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Flutter pub get
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk    

 
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
          
      - name: Upload All files
        uses: actions/upload-artifact@v3
        with:
          name: outputs
          path: build/app/outputs/*
          
      - name: Send Notification
        uses: actions/github-script@v4
        with:
          script: |
            const child_process = require('child_process');
            child_process.execSync(
              `echo "Your GitHub Action has finished." | sendmail -s "Action Notification" babai.sadra@gmail.com`
            );
